services:
  matleo_bank_statement_parser.pdf_reader:
    class: Matleo\BankStatementParserBundle\PdfReader
    public: false

  matleo_bank_statement_parser.bank_statement_parser:
    class: Matleo\BankStatementParserBundle\BankStatementParser
    arguments:
      $pdfReader: '@matleo_bank_statement_parser.pdf_reader'

  Matleo\BankStatementParserBundle\BankStatementParser: '@matleo_bank_statement_parser.bank_statement_parser'
