language: php

php:
  - 7.2

install: composer install --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - php bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: matthieu.leorat@pm.me