language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - PHPUNIT_FLAGS="-v"

matrix:
  fast_finish: true
  include:
      # Test the latest stable release
    - php: 7.2
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-clover=coverage.clover"

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/phpunit --coverage-clover="coverage.clover"

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
